### ISSUE TITLE
Compiling RLDOCK (not RLDOCK_Original)

### ISSUE THREAD

**Issue by filipsPL** [Vfold-RNA/RLDOCK#1]
When using `RLDOCK_Original` it seems that I don't get the output conformation mol2 files (which works fine for `RLDOCK`). Unfortunatelly on my target system provided binary of `RLDOCK` doesn't work. Is there a way to get it compiled, or to force `RLDOCK_Original` to produce output conformation mol2 files?

**Comment by Vfold-RNA** [comment]
Thank you for using our docking tool.

We will enable `RLDOCK_original` to output mol2 files for users' convenience. It is supposed to take 10 days for this update. Once the update is complete, we will proceed to notify you.

**Comment by Vfold-RNA** [comment]
@filipsPL Thanks again for using our docking tool. The update is complete, now `RLDOCK_original` could output mol2 files.

**Comment by filipsPL** [comment]
thanks, it works! :+1:
