### ISSUE TITLE
About output files 

### ISSUE THREAD

**Issue by gongxq19** [Vfold-RNA/RLDOCK#2]
Hi,
  How to generate conformations of the output files after RLDOCK docking? Could you please provide a script to generate the conformations?
  Looking forward to your reply!

**Comment by Yuanzhe-Zhou** [comment]
Hi,

Do you mean a script that can convert poses stored in XXX_SF_low.dat and XXX_SF_high.dat to mol2 format, so one can easily check them using 3D visualization software?

Best,
Yuanzhe

**Comment by yuanzhezhou** [comment]
> Hi,
> How to generate conformations of the output files after RLDOCK docking? Could you please provide a script to generate the conformations?
> Looking forward to your reply!

Hi,

Do you mean a script that can convert poses stored in XXX_SF_low.dat and XXX_SF_high.dat to mol2 format, so one can easily check them using 3D visualization software?

Best,
Yuanzhe

**Comment by gongxq19** [comment]
Yes, I hope I can directly check them using 3D visualization software!

**Comment by yuanzhezhou** [comment]
> Yes, I hope I can directly check them using 3D visualization software!

Hi, I just updated the repo. You can now find **util** folder inside **Examples** folder, and the **readme.md** file inside **util** should tell you how to run the python script. 
Please let me know if this script works for you, and let me know if it can generate the correct mol2 file. Thanks!

**Comment by yuanzhezhou** [comment]
Hi, just a follow-up for this issue. Do the provided script work for you? If it works, I will then close this issue. Thank you.

**Comment by gongxq19** [comment]
Hi, the provided script doesn't work for me, the error is as follows::
  Traceback (most recent call last):
    File "/root/RLDOCK/Examples/util/dump_SF_poses_to_mol2.py", line 105, in <module>
      template_ligand = sys.argv[1]
  IndexError: list index out of range
 Actually, I want to visualize the molecular conformation after docking, but the output file has no conformation information.

**Comment by gongxq19** [comment]
I mean when I use my own system for docking, the output file doesn't generate conformation information.

**Comment by yuanzhezhou** [comment]
The python script needs to be run with arguments. However, I found this may not be very convenient for you. Therefore, I modified the RLDOCK program. 

If you clone this new repo and run the example cases, the RLDOCK will also output XXX_SF_low.mol2 XXX_SF_high.mol2 files, which contain the poses originally stored in XXX_SF_low.dat and XXX_SF_high.dat. 
Please clone this new rep, run your cases, and let me know if this works for you.
Thanks.

**Comment by gongxq19** [comment]
Hi,
This new repo is OK. I can get dock conformation through my cases.
Thank you very much!

**Comment by yuanzhezhou** [comment]
You are welcome!
